language: java
jdk: oraclejdk11

before_script:
  - chmod +x gradlew

before_install:
  - sudo apt-get install sendmail


script:
  gradle build && gradle check  && echo 'hello'

after_failure:
  cat /home/travis/build/grewe/HelloWorld_CS401_Gradle/build/reports/tests/test/index.html &&
  echo "Subject: sendmail test" | sendmail -v my@email.com